name: Release

on:
  push:
    tags:
      - '*'

permissions:
  packages: write

jobs:
  release:
    strategy:
      matrix:
        os: [windows-2022]
    runs-on: ${{ matrix.os }}
    name: Release
    steps:
      - name: Checkout current commit/branch/tag
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install npm dependencies
        run: npm ci
        env:
          NODE_ENV: development

      - name: Lint files
        run: npm run lint

      - name: Typechecks
        run: npm run typecheck

      - name: Prettier check
        run: npm run prettier:check

      - name: Build
        run: npm run build
        env:
          NODE_ENV: production

      - name: Package and publish
        run: npm run package:publish
        env:
          CI: true
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
