name: Version

on:
  workflow_dispatch:

jobs:
  version:
    runs-on: ubuntu-22.04
    name: Version
    steps:
      - name: Checkout current commit/branch/tag
        uses: actions/checkout@v4

      - name: Git setup
        run: |
          # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
          git --version
          git config user.name "Github Actions"
          git config user.email "<>"
          
      - name: Release new version
        run: npm version minor

      - name: Push tag
        run: git push --tags
